<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.1.1
 */

/**
 * Database `db-first`
 */

/* `db-first`.`Auto Usate` */
$Auto_Usate = array(
  array('id' => '1',
          'marca' => 'Honda',
          'modello' => 'Hr-v',
          'kilometri' => '80000',
          'immatricolazione' => '2017-11-21',
          'cambio' => 'Automatico',
          'colore' => 'Nero',
          'condizione' => 'Ottime',
          'prezzo' => '17000'),
  array('id' => '2',
          'marca' => 'Ford',
          'modello' => 'Kuga',
          'kilometri' => '150000',
          'immatricolazione' => '2015-04-08',
          'cambio' => 'Manuale',
          'colore' => 'Blu',
          'condizione' => 'Buone',
          'prezzo' => '13800'),
  array('id' => '3',
          'marca' => 'Audi',
          'modello' => 'A1',
          'kilometri' => '50000',
          'immatricolazione' => '2020-02-18',
          'cambio' => 'Automatico',
          'colore' => 'Giallo',
          'condizione' => 'Ottime',
          'prezzo' => '19900'),
  array('id' => '4',
          'marca' => 'Renault',
          'modello' => 'Arkana',
          'kilometri' => '12000',
          'immatricolazione' => '2021-08-05',
          'cambio' => 'Automatico',
          'colore' => 'Arancione',
          'condizione' => 'Come nuova',
          'prezzo' => '29990'),
  array('id' => '5',
          'marca' => 'Peugeot',
          'modello' => '206',
          'kilometri' => '190000',
          'immatricolazione' => '2009-06-14',
          'cambio' => 'Manuale',
          'colore' => 'Azzurro',
          'condizione' => 'Buone',
          'prezzo' => '4500'),
  array('id' => '6',
          'marca' => 'Volkswagen',
          'modello' => 'Golf 7',
          'kilometri' => '60000',
          'immatricolazione' => '2018-01-22',
          'cambio' => 'Automatico',
          'colore' => 'Bianco',
          'condizione' => 'Ottime',
          'prezzo' => '16900'),
  array('id' => '7',
          'marca' => 'Alfaromeo',
          'modello' => 'Giulia',
          'kilometri' => '35000',
          'immatricolazione' => '2018-10-30',
          'cambio' => 'Manuale',
          'colore' => 'Rosso',
          'condizione' => 'Come nuova',
          'prezzo' => '32000'),
  array('id' => '8',
          'marca' => 'Opel',
          'modello' => 'Astra',
          'kilometri' => '110000',
          'immatricolazione' => '2013-09-09',
          'cambio' => 'Manuale',
          'colore' => 'Grigio',
          'condizione' => 'Buone',
          'prezzo' => '8500')
);
